### ISSUE TITLE
Please add 

### ISSUE THREAD

**Issue by sekendar1337** [Sxlitude/antinuke#4]
Ban limit - ex: bot will set ban limit means bot/admin can ban 1 member in a hr or something if he try to ban more he will get timeout or muted and bot will send log to server owner.

Add.
Anti link
anti dc invite
anti nude images
andi ping
etc

**Comment by Sxlitude** [comment]
this src will not be updated from now.

**Comment by Kroniclz** [comment]
you how to fix the problem when the bot randomly turns off and then just stops working after a while
