### ISSUE TITLE
why

### ISSUE THREAD

**Issue by dylanjamesdev** [Sxlitude/antinuke#5]
why dont u just release the typescript code? this looks like obfuscated compiled typescript from an build output folder

**Comment by WindowsCmd** [comment]
bump

Can't you see the unobfuscated code in the previous commits? Whats the point?

**Comment by Sxlitude** [comment]
actually i'm gonna bring back the code to normal, in a few hours.

**Comment by Sxlitude** [comment]
The code of both the branches is now normal. though i really wanted to do it but was procrastinating. i was not in the mood to obfuscate the code, but i had to do it forcefully as people easily edit the code and claim that as theirs. but i was also having trouble editing such a code.

**Comment by Sxlitude** [comment]
@dylanjamesdev & @WindowsCmd , 
I'm gonna close this issue due to inactivity in 24 hours.

**Comment by Sxlitude** [comment]
well I waited for 80+ hours. due to no response im finally closing this issue
